// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0DIMgU5RwGoKedE68K4iWTft1XAuXs9c',
    appId: '1:144690156112:web:623a40fd0b8345b460f755',
    messagingSenderId: '144690156112',
    projectId: 'atyourpace-6a6e5',
    authDomain: 'atyourpace-6a6e5.firebaseapp.com',
    storageBucket: 'atyourpace-6a6e5.firebasestorage.app',
    measurementId: 'G-4P0NJDRL77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDcvZAKR3sNOMgL0JlGkCLGtUGYakUbB0',
    appId: '1:144690156112:android:004d50a8aac3150660f755',
    messagingSenderId: '144690156112',
    projectId: 'atyourpace-6a6e5',
    storageBucket: 'atyourpace-6a6e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAeZgg5wVFzwStV5pC6_zrOb-wufQJaKA',
    appId: '1:144690156112:ios:1a3d73abf1784c2260f755',
    messagingSenderId: '144690156112',
    projectId: 'atyourpace-6a6e5',
    storageBucket: 'atyourpace-6a6e5.firebasestorage.app',
    iosBundleId: 'com.ayp.aypTourGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0DIMgU5RwGoKedE68K4iWTft1XAuXs9c',
    appId: '1:144690156112:web:fffef2bdb5ec0e1d60f755',
    messagingSenderId: '144690156112',
    projectId: 'atyourpace-6a6e5',
    authDomain: 'atyourpace-6a6e5.firebaseapp.com',
    storageBucket: 'atyourpace-6a6e5.firebasestorage.app',
    measurementId: 'G-NS3P9CD70P',
  );
}
